=== ul2002/multiple-role-blog/documentations/schemas/users/get-responses-200.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "http://localhost/api-doc/schemas/",
    "type": "array",
    "description": "The list of users.",
    "items": {
      "type": "object",
      "properties": {
         "id" : {
          "type": "string",
          "description": "User id"
        },
         "firstname": {
          "type": "string",
          "description": "User firstname"
        },
        "lastname" : {
          "type": "string",
          "description": "User lastname"
        },
         "email" : {
          "type": "string",
          "description": "User email address",
          "format": "email"
        },
        "phone" : {
          "type": "string",
          "description": "User phone"
        },
        "role" : {
          "type": "string",
          "enum": ["MEMBER", "MANAGER", "ADMIN"],
          "description": "User role"
        },
        "gender" : {
          "type": "string",
          "enum": ["male", "female"],
          "description": "User gender"
        }
      },
     "required": [ "id","firstname", "lastname", "email", "role", "gender", "phone"]
    }
    
}

=== ul2002/multiple-role-blog/documentations/examples/users/get-responses-200.json
[
    {
      "id": "1",
      "email": "ulrich@example.com",
      "firstname" : "ulrich",
      "lastname" : "ntella",
      "phone" : "678976545",
      "role" : "MEMBER",
      "gender" : "male"
    },
    {
      "id": "2",
      "email": "lea@example.com",
      "firstname" : "leo",
      "lastname" : "max",
      "phone" : "670979655",
      "role" : "MEMBER",
      "gender" : "male"
    }
]
